= Ribose Encrypted Tokens
:docnumber: XXXXX
:tc-document-number: 9999
:edition: 1
:ref-docnumber: RS 11002:2018(E)
:copyright-year: 2018
:revdate: 20180802T00:00:00Z
:language: en
:script: Latn
:title: Information security technology -- Time-sensitive authenticated encrypted tokens
:doctype: standard
:status: draft-standard
:technical-committee: Security
:draft:
:toc:
:stem:
:xrefstyle: short

.Foreword

Ribose is the asymmetric security company.

Ribose Group Inc. ("Ribose") is global developer of _asymmetric security_ technologies across user-centric systems and applications.

Ribose works closely with international organizations such as ISO, CalConnect and the Cloud Security Alliance.

The procedures used to develop this document and those intended for its further maintenance are described in the Ribose Standardization Directives.

In particular the different approval criteria needed for the different types of Ribose documents should be noted. This document was drafted in accordance with the
editorial rules of the Ribose Standardization Directives.

Attention is drawn to the possibility that some of the elements of this
document may be the subject of patent rights. Ribose shall not be held responsible
for identifying any or all such patent rights. Details of any patent rights
identified during the development of the document will be in the Introduction.

Any trade name used in this document is information given for the convenience
of users and does not constitute an endorsement.

This document was prepared by the Ribose Committee _{technical-committee}_.



== Introduction



== Scope



[bibliography]
== Normative references

This document does not contain any normative references.


== Terms, definitions, symbols and abbreviated terms

=== Terms and definitions

==== user

person that utilizes a service

==== forward secrecy

method such that user of revoked access is unable to access data
created after access revocation

NOTE: https://tools.ietf.org/html/rfc7525#section-6.3


==== blockcipher

encryption algorithm that encrypts a plaintext into an equivalent
sized ciphertext, using an identical key for encryption and
decryption


=== Symbols

// TODO: need these?

stem:[E(K, m)]::
  Encryption of the message stem:[m] using the key stem:[K].

stem:[PE(K, m)]::
  Encryption of the message stem:[m] using the key stem:[K].

stem:[BCE(K, m)]::
  Symmetric encryption, through the blockcipher stem:[BC], of the message
  stem:[m] using the key stem:[K].

stem:[BCD(K, m)]::
  Symmetric decryption, through the blockcipher stem:[BC], of the message
  stem:[m] using the key stem:[K].


== Example flow

* + : can be a structured concatenation, e.g. merging of a JSON hash

== token generation

server time block = n-second blocks (e.g. 00:00 to 00:05, 00:05 to 00:10, etc)

* reason for blocks: so as to reduce the possible space of valid tokens from nanosecond-(?)blocks to e.g. 5-second blocks

unauthenticated token = Encrypt(server secret, client nonce + server time block)

* server secret: only the server can reliably generate valid tokens
* client nonce: uniqueness? probably only needs to be unique within a user's client pool (TBD). Only the client needs to store it.
* server time block: for server to determine whether token has expired

* expires when (24 hrs / 5 seconds) blocks have passed.

authenticated token = Encrypt(server secret, user id + client nonce + server time block)

* user id: something for the server user database to identify the user with

authenticated token with server-controlled expiration = Encrypt(server secret, user id + client nonce + server time block, number of remaining valid server time blocks)

* number of valid server time blocks:
** Puts the control of "remember me" back to server
** Server sets it
** whenever Server receives such a token, Server needs to calculate a new 'number of remaining valid server time blocks' so token would really expire after e.g. 7 days

server secret = ...

=== Expiration

E.g. 24 hours

But more usefully, 7 days (mimicking the remember-me function).

* How would this affect collision space?

=== 

but every time client sends a request to server, server 

=== Unauthenticated -> unauthenticated

TODO: verify usefulness for pre-login CSRF?

client -> server: client nonce (????)
server -> client: unauthenticated token

=== Unauthenticated -> authenticated

client -> server: (username + password / API token), client nonce
server -> client: authenticated token

DONE

=== auth'd -> next request (not yet expired, within same server time block)

no new token needed

DONE

=== auth'd -> next request (not yet expired, not within same server time block)

==== Scenario

* My token has an expiration time of 24 hours.
* I present my token to server at the 23rd hour.
* The server now needs to generate a new token with a further 24-hour expiration time for me to use in my next request.

new token : generated with ...
OTP token

* Why OTP now?

// server-client OTP seed = Encrypt??(server master secret, server time block + user id)
server-client OTP token = Encrypt??(server master secret, server time block + user id)

* server master secret: 1) So that only server can reliably generate OTP tokens. 2) tends not to change much.
* user id : so that OTP seed is specific to each user
* server time block: the natural input for OTP
// * client time block: the natural input for OTP. Client needs to sync time with server (TBI)

// server -> client: server-client OTP seed
// client -> server: Encrypt(???)(server-client OTP seed, client time block)
authenticated token 2 = Encrypt(server secret, user id + client nonce + server-client OTP token + server time block)
server -> client: server-client OTP token
client -> server: server-client OTP token, client nonce

* client nonce: can be old / new. non-consequential.

= Questions

* Q1: If I as a client has two tokens, A and B, where expiration(A) < expiration(B).  Why should I bother to use B instead of A, where the expiration is 24 hours (or even 7 days)?
* A1: It's really up to the client.  If client keeps using A, it risks expiration sooner than entitled.
* Q2: How does this scheme deal with the issue solved by per-request changing of tokens?
* A2: 

=== auth'd -> next request (expired)


[bibliography]
== Bibliography

// * [[[RSASHARE,Shared generation of RSA keys]]] Michael Malkin, Thomas D. Wu, Dan Boneh. _Experimenting with Shared Generation of RSA keys_. NDSS 1999.



[annex]
== Sample Annex

Sample annex text
