= Ribose Encrypted Tokens
:docnumber: XXXXX
:tc-document-number: 9999
:edition: 1
:ref-docnumber: RS 11002:2018(E)
:copyright-year: 2018
:revdate: 20180802T00:00:00Z
:language: en
:script: Latn
:title: Information security technology -- Time-sensitive authenticated encrypted tokens
:doctype: standard
:status: draft-standard
:technical-committee: Security
:draft:
:toc:
:stem:
:xrefstyle: short

.Foreword

[plantuml]
....
@startuml
!include ../models/style.uml.inc
Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response

Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response
@enduml
....

Ribose is the asymmetric security company.

Ribose Group Inc. ("Ribose") is global developer of _asymmetric security_ technologies across user-centric systems and applications.

Ribose works closely with international organizations such as ISO, CalConnect and the Cloud Security Alliance.

The procedures used to develop this document and those intended for its further maintenance are described in the Ribose Standardization Directives.

In particular the different approval criteria needed for the different types of Ribose documents should be noted. This document was drafted in accordance with the
editorial rules of the Ribose Standardization Directives.

Attention is drawn to the possibility that some of the elements of this
document may be the subject of patent rights. Ribose shall not be held responsible
for identifying any or all such patent rights. Details of any patent rights
identified during the development of the document will be in the Introduction.

Any trade name used in this document is information given for the convenience
of users and does not constitute an endorsement.

This document was prepared by the Ribose Committee _{technical-committee}_.



== Introduction

=== User requirements:

. U1: batch requests should not have degraded performance
. U2: the same scheme should work in both browser & native mobile app (i.e. without "session")

=== Security requirements:

Assumptions

. A1: user authentication implemented using username + password

General

. S1: CSRF protection during pre-login (unauthenticated) & post-login (authenticated)
. S2: Sessions with expiration (e.g. 7 days)
. S3: Client: if needed, can store whatever tokens in cookie / local storage
. S4: Server: if needed, can store whatever tokens in DB

Technical

. S5: "forward validity" of CSRF token
.. Getting hold of an old CSRF token would have minimal impact on the attacker's ability to forge subsequent requests

TODO:
- define: user, client, session, token, validity
: from ietf / iso source (prefer iso?)
- define: time block: in 8601, has timescale/time interval concept. link?  
  need to define/include begin-end?
- specify time granularity
- specify how to sync time between client & server?
	- 1) ask client to enter the next otp
	  2) if opt valid, store it in DB along with User / client
	  3) calculate time block difference between stored otp and current server time block.
	  4) store this time block difference in DB along with User / client
	  5) Next time client presents an otp, server can use this time block difference as a window.
	- need to assume that the client doesn't have a purposefully set wrong 
	  time (e.g. several years apart)?
	  - Maybe not. We can just set a small enough window e.g. 10 days in which to 
	    search.
- specify what to do when times drift: irrelevant.
- mark as concern: certain ranges of values (params) might cause problems
  e.g. validity time window, expiry
  More like UX problems.  Obviously not too short e.g. 1 sec.
- define: diff kinds of expiry
  - A: OTP seed expiration.
- How to handle batch requests?
- flow diagrams for every single flow
- specify how to encrypt
  e.g. fixed-length vs var-length.
  e.g. ffxcodec has more variable length ciphertext
- low vs high latency (e.g. LAN vs satellite)
- 

== Scope



[bibliography]
== Normative references

This document does not contain any normative references.


== Terms, definitions, symbols and abbreviated terms

=== Terms and definitions

==== user

person that utilizes a service

==== forward secrecy

method such that user of revoked access is unable to access data
created after access revocation

NOTE: https://tools.ietf.org/html/rfc7525#section-6.3


==== blockcipher

encryption algorithm that encrypts a plaintext into an equivalent
sized ciphertext, using an identical key for encryption and
decryption


=== Symbols

// TODO: need these?

stem:[E(K, m)]::
  Encryption of the message stem:[m] using the key stem:[K].

stem:[PE(K, m)]::
  Encryption of the message stem:[m] using the key stem:[K].

stem:[BCE(K, m)]::
  Symmetric encryption, through the blockcipher stem:[BC], of the message
  stem:[m] using the key stem:[K].

stem:[BCD(K, m)]::
  Symmetric decryption, through the blockcipher stem:[BC], of the message
  stem:[m] using the key stem:[K].


== Example flow

* + : can be a structured concatenation, e.g. merging of a JSON hash

=== token generation

server time block = n-second blocks (e.g. 00:00 to 00:05, 00:05 to 00:10, etc)

* reason for blocks: so as to reduce the possible space of valid tokens from nanosecond-(?)blocks to e.g. 5-second blocks

unauthenticated token = Encrypt(server secret, client nonce + server time block)

* server secret: only the server can reliably generate valid tokens
* client nonce: uniqueness? probably only needs to be unique within a user's client pool (TBD). Only the client needs to store it. Must be a cryptographically strong pseudo-random value to prevent brute-force attacks on 'server secret'.
* server time block: for server to determine whether token has expired

* expires when (24 hrs / 5 seconds) blocks have passed.

authenticated token = Encrypt(server secret, user id + client nonce + server time block)

* user id: something for the server user database to identify the user with

authenticated token with server-controlled expiration = Encrypt(server secret, user id + client nonce + server time block, number of remaining valid server time blocks)

* number of valid server time blocks:
** Puts the control of "remember me" back to server
** Server sets it
** whenever Server receives such a token, Server needs to calculate a new 'number of remaining valid server time blocks' so token would really expire after e.g. 7 days

server secret = ...

=== Expiration

E.g. 24 hours

But more usefully, 7 days (mimicking the remember-me function).

* How would this affect collision space?

=== 

but every time client sends a request to server, server 

=== Unauthenticated -> unauthenticated

Not useful.
// verify usefulness for pre-login CSRF?
//
// client -> server: client nonce (????)
// server -> client: unauthenticated token
// client -> server: Payload + unauthenticated token

=== Unauthenticated -> authenticated

client -> server: (username + password / API token), client nonce
server -> client: authenticated token (optional: with server-controlled expiration, e.g, via "Remember me")
client -> server: Payload + authenticated token

DONE

=== auth'd -> next request (not yet expired, within same server time block)

no new token needed

client -> server: Payload + authenticated token

DONE

=== auth'd -> next request (not yet expired, not within same server time block)

==== Scenario

* My token has an expiration time of 24 hours.
* I present my token to server at the 23rd hour.
* The server now needs to generate a new token with a further 24-hour expiration time for me to use in my next request.

new token : generated with ...
OTP token

* Why OTP now?

// server-client OTP seed = Encrypt??(server master secret, server time block + user id)
server-client OTP token = Encrypt??(server master secret, server time block + user id)

* server master secret: 1) So that only server can reliably generate OTP tokens. 2) tends not to change much.
* user id : so that OTP seed is specific to each user
* server time block: the natural input for OTP
// * client time block: the natural input for OTP. Client needs to sync time with server (TBI)

// server -> client: server-client OTP seed
// client -> server: Encrypt(???)(server-client OTP seed, client time block)
authenticated token 2 = Encrypt(server secret, user id + client nonce + server-client OTP token + server time block)
server -> client: server-client OTP token
client -> server: server-client OTP token, client nonce

* client nonce: can be old / new. non-consequential.

(^ irrelevant)

=== auth'd -> next request (expired)

TODO:

= Questions

* Q1: If I as a client has two tokens, A and B, where expiration(A) < expiration(B).  Why should I bother to use B instead of A, where the expiration is 24 hours (or even 7 days)?
* A1: It's really up to the client.  If client keeps using A, it risks expiration sooner than entitled.
* Q2: How does this scheme deal with the issue solved by per-request changing of tokens (e.g. Devise Token Auth)?
* A2: The issue that would occur if tokens are kept the same throughout a session, is that if one token got compromised, the attacker would be able to forge subsequent requests.
Schemes employed by Devise Token Auth solves this by changing tokens per request.
This proposed scheme:

** non-expired && non-fresh

[not expired; current time exceeds token's 'server time block']

client -> server: authenticated token
server -> client: Encrypt(server secret, user id + client nonce + new server time block)

* Q3: If we close our tabs in browser. The token stored by client is the latest available to client.  Then we open a new tab, but within the token's expiry.
* A3: 1) Do whatever is done in A2 (non-expired && non-fresh).
* Q4: So that means token A in Q1 can be used over and over until expiry?
* A4: Yes and it needs to be fixed. TODO: TBD

We now use OTP.

== OTP example flow

=== token generation

server time block = n-second blocks (e.g. 00:00 to 00:05, 00:05 to 00:10, etc)

* reason for blocks: so as to reduce the possible space of valid tokens from nanosecond-(?)blocks to e.g. 5-second blocks


* server secret: only the server can reliably generate valid tokens
* client nonce: uniqueness? probably only needs to be unique within a user's client pool (TBD). Only the client needs to store it. Must be a cryptographically strong pseudo-random value to prevent brute-force attacks on 'server secret'.
* server time block: for server to determine whether token has expired

* expires when (24 hrs / 5 seconds) blocks have passed.

authenticated OTP seed = Encrypt(server secret, user id + client nonce + server time block)

* user id: something for the server user database to identify the user with

authenticated OTP seed with server-controlled expiration = Encrypt(server secret, user id + client nonce + server time block, number of remaining valid server time blocks)

(^ TODO: verify usefulness)

* number of valid server time blocks:
** Puts the control of "remember me" back to server
** Server sets it
** whenever Server receives such a token, Server needs to calculate a new 'number of remaining valid server time blocks' so token would really expire after e.g. 7 days

server secret = ...

=== Unauthenticated -> unauthenticated

Most likely irrelevant?

=== Unauthenticated -> authenticated

[given: client & server times are synced]

1. client -> server: (username + password / API token), client nonce
2. server -> client: authenticated OTP seed
3. client -> server: Payload + OTP token = GenerateOTP(authenticated OTP seed, client time block)
4. server: validate?:
	if f(OTP token, server time block, retrieved authenticated OTP seed)
	then true
	else false

where 'retrieved authenticated OTP seed' = DB.getOTPSeed(user id)

but where can 'user id' be retrieved by server?

What if we use encrypted token:

[assume: client already knows its user id???]
3. client -> server: Payload + user id + Encrypted Token = Encrypt(authenticated OTP seed, client time block)

- Question: safe to assume 'user id' can't be forged?
- Answer: Yes. Server can compare the 'authenticated OTP seed' of the claimed 'user id'.

4. server: validate?:
	if (authenticated OTP seed == retrieved authenticated OTP seed)
	then if NotTooFarInTimeBlocks?(client time block, server time block) &&
		SeedIsNotExpired?(authenticated OTP seed, server time block)
	else false

where 'retrieved authenticated OTP seed' = DB.getOTPSeed(user id)
where 'authenticated OTP seed', 'client time block' = Decrypt(retrieved authenticated OTP seed, Encrypted Token)

==== Questions

* Q1: So that means the security of this scheme hinges on that of the 'authenticated OTP seed'?  Since once the seed is compromised, there is no way to tell if requests are forged (up to the expiration datetime).
* A1:

==== Back to Unauth -> auth

What if we use the generated token as seed for next token?

3. client -> server: Payload + user id + Encrypted Token = Encrypt(authenticated OTP seed, client time block)
4. server stores 'authenticated OTP seed' + 'Encrypted Token' + 'client time block'  in DB for 'user id'
and validate(...)

- server stores 'client time block' along with 'Encrypted Token' so that in subsequent resquests, if there's an out-of-order request that is still within certain valid threshold, the server will know to not overwrite its stored encrypted token (by comparing the two 'client time blocks').

=== auth'd -> next request (not yet expired; regardless of server time block)

and then later:

2. server -> client: Encrypted Token
3. client -> server: Payload + user id + Encrypted Token 2 = Encrypt(Encrypted Token, client time block)

4. server stores 'authenticated OTP seed' + 'Encrypted Token2' + 'client time block' in DB for 'user id'
then validate:
	if (authenticated OTP seed == retrieved authenticated OTP seed)
	then if NotTooFarInTimeBlocks?(client time block, server time block) &&
		SeedIsNotExpired?(authenticated OTP seed, server time block)
	else false

where 'retrieved authenticated OTP seed' = DB.getOTPSeed(user id)
where 'authenticated OTP seed', 'client time block' = Decrypt(retrieved authenticated OTP seed, Encrypted Token)

=== auth'd -> next request (expired)

* "Expired" means the expiration datetime encoded inside 'authenticated OTP seed' is expired...

	SeedIsNotExpired?(authenticated OTP seed, server time block)

* This means the seed needs refreshing? or the user needs to re-authenticate?

The user needs to re-authenticate (server returns 401).

^ The above scheme requires client time block syncing.

==== More OTP

*  The following scheme makes syncing of client time block unnecessary.
*  It also forces the client to swap out its old keys with the latest one as the server knows that only one token is valid at a time and it happens to be the latest one.

2. server -> client: Encrypted Token C = Encrypt(authenticated OTP seed, server time block)
server stores 'authenticated OTP seed' + 'Encrypted Token C' in DB for 'user id'
3. client -> server: Payload + user id + Encrypted Token C
4. 
server validate:
	if IsGivenTimeBlockInCurrentTimeBlock?(time block)
		respond with Encrypted Token C
	else
		respond with Encrypted Token C 2 = Encrypt(retrieved authenticated OTP seed, current server time block)
		server stores 'authenticated OTP seed' + 'Encrypted Token C 2' in DB for 'user id'

where 'time block' = Decrypt(retrieved authenticated OTP seed, Encrypted Token C)
where 'retrieved authenticated OTP seed' = DB.getOTPSeed(user id)

*  or... use current token as key input to Encrypt?

2. server -> client: Encrypted Token C = Encrypt(authenticated OTP seed, server time block)
server stores 'authenticated OTP seed' + 'Encrypted Token C' in DB for 'user id'
3. client -> server: Payload + user id + Encrypted Token C
4. 
server validate:
	if Hash(Received Token) != DB.getStoredHashedToken (== Hash(Encrypted Token C))
		respond with 401
	if IsGivenTimeBlockInCurrentTimeBlock?(time block)
		respond with Encrypted Token C
	else
		val token = Encrypted Token C
		respond with Encrypted Token C 2 = Encrypt(Encrypted Token C, current server time block + random value)
		server stores 'authenticated OTP seed' + 'Encrypted Token C' + 'Hash(Encrypted Token C 2)' in DB for 'user id'

where 'time block' = Decrypt(Current Token, Encrypted Token C)
where 'Current Token' = DB.getStoredToken(user id) == authenticated OTP seed

* meaning at the start, DB would store 'authenticated OTP seed' + 'authenticated OTP seed' + 'Hash(Encrypted Token C)' in DB for 'user id'

and then:

3. client -> server: Payload + user id + Encrypted Token C 2
4. server validate:
	if Hash(Received Token) != DB.getStoredHashedToken (== Hash(Encrypted Token C 2))
		respond with 401
	if IsGivenTimeBlockInCurrentTimeBlock?(time block)
		respond with Encrypted Token C 2
	else
		respond with Encrypted Token C 3 = Encrypt(Encrypted Token C 2, current server time block + random value)
		server stores 'authenticated OTP seed' + 'Encrypted Token C 2' + 'Encrypted Token C 3' in DB for 'user id'

where 'time block' = Decrypt(Current Token, Encrypted Token C 2)
where 'Current Token' = DB.getStoredToken(user id) == Encrypted Token C

* meaning at the start, DB would store 'authenticated OTP seed' + 'Encrypted Token C' + 'Hash(Encrypted Token C 2)' in DB for 'user id'
* random value: to prevent attacker from generating new valid tokens from old tokens (e.g. if stolen from a DB)
* Hash(Current Encrypted Token): to prevent attacker from directly using it to impersonate users

TODO: Need to make it handle batch requests.  Add some kind of window? concerns for concurrent DB access to remove the same old token?

== Use of cookie

=== HttpOnly

* assumptions: set to 'true'

Pros

* JS cannot read its values.
* Together with headers, our own JS can have access to whatever value is needed.

Cons

* Headers need to be set in addition to cookie.

=== Secure

TODO

* assumptions:

Pros


Cons


== Scenarios

=== 1

* Attacker site
* Assumptions:
** All encrypted tokens are stored only in browser tab's JS variables, not in cookie / local storage

Pros

* Attacker site has no way to access the tokens, protected by browser's own containing mechanism

Cons

* User does not have the ability to use multiple browser tabs with a single authentication
* User would immediately lose the existing 'session' once the current browser tab is closed.

=== 2

* Attacker site
* Assumptions:
** 1) cookie: `HttpOnly` set to `true`
** 2) All encrypted tokens are stored in browser cookie
** 3) No cross-origin checking by browser
** 4) Browser honours `HttpOnly` flag
** 5) Cookie values are also set in response header
** 6) Cookie values (from previous response header) are also set in request header
** 7) Server only accepts requests with the cookie and header both set with the same value

Pros

* Attacker JS cannot access cookie values (by 1, 2, 4) even with 3.
*

Cons

* New browser tab won't be able to submit cookie value in request header (by 7) 
  thus needs to re-authenticate (but with stale value still in cookie?)

=== 3

* Attacker site
* Assumptions:
** 1) cookie: `HttpOnly` set to `true`
** 2) All encrypted tokens are stored in browser local storage
** 3) No cross-origin checking of requests by browser
** 4) Attacker has no access to the app's local storage (as attacker site is in a different origin)
** 5) Token to be set in request header
** 6) Token can be set in hidden <input> in a form if 5) cannot be achieved
** 7) Server only accepts requests with token in header or from hidden <input>

Pros

* 

Cons

* 

=== 4

* Assumptions:
** 1) cross-origin checking is disabled

* Q: Are all login forms now vulnerable to pre-login CSRF?
* A: Yes.


[bibliography]
== Bibliography

// * [[[RSASHARE,Shared generation of RSA keys]]] Michael Malkin, Thomas D. Wu, Dan Boneh. _Experimenting with Shared Generation of RSA keys_. NDSS 1999.



[annex]
== Sample Annex

Sample annex text
