= Ribose Encrypted Tokens
:docnumber: XXXXX
:tc-document-number: 9999
:edition: 1
:ref-docnumber: RS 11002:2018(E)
:copyright-year: 2018
:revdate: 20180802T00:00:00Z
:language: en
:script: Latn
:title: Information security technology -- Time-sensitive authenticated encrypted tokens
:doctype: standard
:status: draft-standard
:technical-committee: Security
:draft:
:toc:
:stem:
:xrefstyle: short

.Foreword

Ribose is the asymmetric security company.

Ribose Group Inc. ("Ribose") is global developer of _asymmetric security_ technologies across user-centric systems and applications.

Ribose works closely with international organizations such as ISO, CalConnect and the Cloud Security Alliance.

The procedures used to develop this document and those intended for its further maintenance are described in the Ribose Standardization Directives.

In particular the different approval criteria needed for the different types of Ribose documents should be noted. This document was drafted in accordance with the
editorial rules of the Ribose Standardization Directives.

Attention is drawn to the possibility that some of the elements of this
document may be the subject of patent rights. Ribose shall not be held responsible
for identifying any or all such patent rights. Details of any patent rights
identified during the development of the document will be in the Introduction.

Any trade name used in this document is information given for the convenience
of users and does not constitute an endorsement.

This document was prepared by the Ribose Committee _{technical-committee}_.



== Introduction



== Scope



[bibliography]
== Normative references

This document does not contain any normative references.


== Terms, definitions, symbols and abbreviated terms

=== Terms and definitions

==== user

person that utilizes a service

==== forward secrecy

method such that user of revoked access is unable to access data
created after access revocation

NOTE: https://tools.ietf.org/html/rfc7525#section-6.3


==== blockcipher

encryption algorithm that encrypts a plaintext into an equivalent
sized ciphertext, using an identical key for encryption and
decryption


=== Symbols

// TODO: need these?

stem:[E(K, m)]::
  Encryption of the message stem:[m] using the key stem:[K].

stem:[PE(K, m)]::
  Encryption of the message stem:[m] using the key stem:[K].

stem:[BCE(K, m)]::
  Symmetric encryption, through the blockcipher stem:[BC], of the message
  stem:[m] using the key stem:[K].

stem:[BCD(K, m)]::
  Symmetric decryption, through the blockcipher stem:[BC], of the message
  stem:[m] using the key stem:[K].



[bibliography]
== Bibliography

// * [[[RSASHARE,Shared generation of RSA keys]]] Michael Malkin, Thomas D. Wu, Dan Boneh. _Experimenting with Shared Generation of RSA keys_. NDSS 1999.



[annex]
== Sample Annex

Sample annex text
